name: flutter_tree_sitter
description: "Tree-sitter for flutter, supports android, ios, linux, macos, windows."
version: 0.0.1
homepage: https://github.com/qiuxiang/flutter-tree-sitter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

ffigen:
  name: "TreeSitter"
  output: "lib/src/bindings.g.dart"
  compiler-opts:
    - "-Isrc/include"
  headers:
    entry-points:
      - "./src/flutter_tree_sitter.c"
  exclude-all-by-default: true
  functions:
    include:
      - "ts_.*"
  globals:
    include:
      - "ts_.*"
  macros:
    include:
      - "TREE_SITTER_.*"
