name: release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Build
        run: |
          make init
          cd example
          flutter create . --platforms linux
          flutter build linux
      - name: Update changelog
        run: |
          export version=$(echo ${{ github.ref_name }} | sed s/v//)
          sed -i -r "s/version: .*/version: $version/" pubspec.yaml
          git tag --format=$'## %(refname:short)\n%(subject)\n' --sort=-v:refname > CHANGELOG.md
      - run: dart pub publish -f
