name: release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
jobs:
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update changelog
        run: |
          export version=$(echo ${{ github.ref_name }} | sed s/v//)
          sed -i -r "s/version: .*/version: $version/" pubspec.yaml
          git tag --format=$'## %(refname:short)\n%(subject)\n' --sort=-v:refname > CHANGELOG.md
      - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
      - run: dart pub publish -f
